# Generated by Django 4.2.5 on 2023-10-02 11:02
import csv
import datetime

from django.db import migrations

from movies.models import Movie, MovieStatistics


def load_initial_data(apps, schema_editor):
    with open('movies/migrations/movies.csv', 'r', encoding='utf-8') as all_movies_file:
        all_movies_file.readline()
        reader = csv.reader(all_movies_file, delimiter=',')

        for row in reader:
            statistics = MovieStatistics(vote_average=float(row[17]), vote_count=int(row[16]), popularity=float(row[2]))
            movie = Movie(tmdb_id=row[1], original_title=row[5], overview=row[11],
                          release_date=datetime.datetime.strptime(row[15], '%m/%d/%Y'),
                          cast=row[6], genres=row[13], director=row[8], keywords=row[10])
            statistics.save()
            movie.statistics = statistics
            movie.save()


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data)
    ]
